### ISSUE TITLE
Tests not communicating with Learn.co

### ISSUE THREAD

**Issue by alexbujenita** [learn-co-curriculum/fewpjs-iterators-filter-lab#5]
As all of the labs that open a webpage for the tests, this one as well doesn't work.

Tests either passing or failing, Learn.co doesn't acknowledge that.

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
